name: SYCL Linux pre-commit build task
# We need to separate build and E2E/CTS tests because the latter might require
# secrets access (for AWS) and that isn't available for pull_request trigger.

on:
  pull_request:

jobs:
  debug_print:
    runs-on: [Linux, build]
    steps:
      - run: echo "${{ toJSON(github)}}"

  detect_changes:
    uses: ./.github/workflows/sycl_detect_changes.yml

  lint:
    needs: [detect_changes]
    runs-on: [Linux, build]
    container:
      image: ghcr.io/intel/llvm/sycl_ubuntu2204_nightly:no-drivers
      options: -u 1001:1001
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}
        sparse-checkout: |
          devops/actions/cached_checkout
          devops/actions/clang-format
          devops/actions/cleanup
    - name: Register cleanup after job is finished
      uses: ./devops/actions/cleanup
    - name: 'PR commits + 2'
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 2 ))" >> "${GITHUB_ENV}"
    - uses: ./devops/actions/cached_checkout
      with:
        path: src
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}
        ref: ${{ github.event.pull_request.head.sha }}
        merge_ref: ''
        cache_path: "/__w/repo_cache/"
    - name: Run clang-format
      uses: ./devops/actions/clang-format
      with:
        path: src

  build:
    name: Linux Build
    # Only build and test patches, that have passed all linter checks, because
    # the next commit is likely to be a follow-up on that job.
    needs: [lint, detect_changes]
    if: |
      always()
      && (success() || contains(github.event.pull_request.labels.*.name, 'ignore-lint'))
    uses: ./.github/workflows/sycl_linux_build_and_test.yml
    secrets: inherit
    with:
      build_ref: ${{ github.event.pull_request.head.sha }}
      merge_ref: ${{ github.event.pull_request.base.sha }}
      build_cache_root: "/__w/"
      build_artifact_suffix: "default"
      build_cache_suffix: "default"
      # changes: ${{ needs.detect_changes.outputs.filters }}
      changes: '[]'
