name: SYCL Linux pre-commit tests task

on:
  workflow_run:
    workflows: [SYCL Linux pre-commit build task]
    types:
      - completed

jobs:
  debug_print:
    runs-on: [Linux, build]
    steps:
      - run: echo "${{ toJSON(github)}}"
      - run: echo "${{ toJSON(context)}}"

  aws-start:
    runs-on: ubuntu-20.04
    environment: aws
    outputs:
      label: ${{ steps.aws_action_arg.outputs.LABEL }}
      arg: ${{ steps.aws_action_arg.outputs.ARG }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: devops/actions/aws-ec2
      - run: npm install ./devops/actions/aws-ec2
      - id: aws_action_arg
        run: |
          LABEL=aws_cuda-${{ github.run_id }}-${{ github.run_attempt }}
          echo LABEL="$LABEL" >> $GITHUB_OUTPUT
          echo ARG="[{\"runs-on\":\"$LABEL\",\"aws-ami\":\"ami-01cb0573cb039ab24\",\"aws-type\":[\"g5.2xlarge\",\"g5.4xlarge\"],\"aws-disk\":\"/dev/sda1:64\",\"aws-spot\":\"false\"}]" >> $GITHUB_OUTPUT
      - uses: ./devops/actions/aws-ec2
        with:
          mode: start
          runs-on-list: ${{ steps.aws_action_arg.outputs.ARG }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

  aws-stop:
    needs: [aws-start]
    if: always()
    runs-on: ubuntu-20.04
    environment: aws
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: devops/actions/aws-ec2
      - run: npm install ./devops/actions/aws-ec2
      - uses: ./devops/actions/aws-ec2
        with:
          mode: stop
          runs-on-list: ${{ needs.aws-start.outputs.arg }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
